'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports System.Xml.Schema

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace CFDI32

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3", IsNullable:=False)> _
    Partial Public Class Comprobante

        Private emisorField As ComprobanteEmisor

        Private receptorField As ComprobanteReceptor

        Private conceptosField() As ComprobanteConcepto

        Private impuestosField As ComprobanteImpuestos

        Private complementoField As ComprobanteComplemento

        Private addendaField As ComprobanteAddenda

        Private versionField As String

        Private serieField As String

        Private folioField As String

        Private fechaField As Date

        Private selloField As String

        Private formaDePagoField As String

        Private noCertificadoField As String

        Private certificadoField As String

        Private condicionesDePagoField As String

        Private subTotalField As Decimal

        Private descuentoField As Decimal

        Private descuentoFieldSpecified As Boolean

        Private motivoDescuentoField As String

        Private tipoCambioField As String

        Private monedaField As String

        Private totalField As Decimal

        Private tipoDeComprobanteField As ComprobanteTipoDeComprobante

        Private metodoDePagoField As String

        Private lugarExpedicionField As String

        Private numCtaPagoField As String

        Private folioFiscalOrigField As String

        Private serieFolioFiscalOrigField As String

        Private fechaFolioFiscalOrigField As Date

        Private fechaFolioFiscalOrigFieldSpecified As Boolean

        Private montoFolioFiscalOrigField As Decimal

        Private montoFolioFiscalOrigFieldSpecified As Boolean

        Private _schemaLocation As String = "http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd"

        Public Sub New()
            MyBase.New()
            Me.versionField = "3.2"
        End Sub

        '''<comentarios/>
        Public Property Emisor() As ComprobanteEmisor
            Get
                Return Me.emisorField
            End Get
            Set(value As ComprobanteEmisor)
                Me.emisorField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property Receptor() As ComprobanteReceptor
            Get
                Return Me.receptorField
            End Get
            Set(value As ComprobanteReceptor)
                Me.receptorField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=False)> _
        Public Property Conceptos() As ComprobanteConcepto()
            Get
                Return Me.conceptosField
            End Get
            Set(value As ComprobanteConcepto())
                Me.conceptosField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property Impuestos() As ComprobanteImpuestos
            Get
                Return Me.impuestosField
            End Get
            Set(value As ComprobanteImpuestos)
                Me.impuestosField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property Complemento() As ComprobanteComplemento
            Get
                Return Me.complementoField
            End Get
            Set(value As ComprobanteComplemento)
                Me.complementoField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property Addenda() As ComprobanteAddenda
            Get
                Return Me.addendaField
            End Get
            Set(value As ComprobanteAddenda)
                Me.addendaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(value As String)
                Me.versionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set(value As String)
                Me.serieField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property folio() As String
            Get
                Return Me.folioField
            End Get
            Set(value As String)
                Me.folioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set(value As Date)
                Me.fechaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property sello() As String
            Get
                Return Me.selloField
            End Get
            Set(value As String)
                Me.selloField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property formaDePago() As String
            Get
                Return Me.formaDePagoField
            End Get
            Set(value As String)
                Me.formaDePagoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set(value As String)
                Me.noCertificadoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property certificado() As String
            Get
                Return Me.certificadoField
            End Get
            Set(value As String)
                Me.certificadoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property condicionesDePago() As String
            Get
                Return Me.condicionesDePagoField
            End Get
            Set(value As String)
                Me.condicionesDePagoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property subTotal() As Decimal
            Get
                Return Me.subTotalField
            End Get
            Set(value As Decimal)
                Me.subTotalField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property descuento() As Decimal
            Get
                Return Me.descuentoField
            End Get
            Set(value As Decimal)
                Me.descuentoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property descuentoSpecified() As Boolean
            Get
                Return Me.descuentoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.descuentoFieldSpecified = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property motivoDescuento() As String
            Get
                Return Me.motivoDescuentoField
            End Get
            Set(value As String)
                Me.motivoDescuentoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoCambio() As String
            Get
                Return Me.tipoCambioField
            End Get
            Set(value As String)
                Me.tipoCambioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set(value As String)
                Me.monedaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set(value As Decimal)
                Me.totalField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property tipoDeComprobante() As ComprobanteTipoDeComprobante
            Get
                Return Me.tipoDeComprobanteField
            End Get
            Set(value As ComprobanteTipoDeComprobante)
                Me.tipoDeComprobanteField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property metodoDePago() As String
            Get
                Return Me.metodoDePagoField
            End Get
            Set(value As String)
                Me.metodoDePagoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property LugarExpedicion() As String
            Get
                Return Me.lugarExpedicionField
            End Get
            Set(value As String)
                Me.lugarExpedicionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NumCtaPago() As String
            Get
                Return Me.numCtaPagoField
            End Get
            Set(value As String)
                Me.numCtaPagoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property FolioFiscalOrig() As String
            Get
                Return Me.folioFiscalOrigField
            End Get
            Set(value As String)
                Me.folioFiscalOrigField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property SerieFolioFiscalOrig() As String
            Get
                Return Me.serieFolioFiscalOrigField
            End Get
            Set(value As String)
                Me.serieFolioFiscalOrigField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property FechaFolioFiscalOrig() As Date
            Get
                Return Me.fechaFolioFiscalOrigField
            End Get
            Set(value As Date)
                Me.fechaFolioFiscalOrigField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property FechaFolioFiscalOrigSpecified() As Boolean
            Get
                Return Me.fechaFolioFiscalOrigFieldSpecified
            End Get
            Set(value As Boolean)
                Me.fechaFolioFiscalOrigFieldSpecified = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property MontoFolioFiscalOrig() As Decimal
            Get
                Return Me.montoFolioFiscalOrigField
            End Get
            Set(value As Decimal)
                Me.montoFolioFiscalOrigField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property MontoFolioFiscalOrigSpecified() As Boolean
            Get
                Return Me.montoFolioFiscalOrigFieldSpecified
            End Get
            Set(value As Boolean)
                Me.montoFolioFiscalOrigFieldSpecified = value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttribute([Namespace]:=XMLSchema.InstanceNamespace)>
        Public Property schemaLocation As String
            Get
                Return _schemaLocation
            End Get
            Set(value As String)
                _schemaLocation = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteEmisor

        Private domicilioFiscalField As t_UbicacionFiscal

        Private expedidoEnField As t_Ubicacion

        Private regimenFiscalField() As ComprobanteEmisorRegimenFiscal

        Private rfcField As String

        Private nombreField As String

        '''<comentarios/>
        Public Property DomicilioFiscal() As t_UbicacionFiscal
            Get
                Return Me.domicilioFiscalField
            End Get
            Set(value As t_UbicacionFiscal)
                Me.domicilioFiscalField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property ExpedidoEn() As t_Ubicacion
            Get
                Return Me.expedidoEnField
            End Get
            Set(value As t_Ubicacion)
                Me.expedidoEnField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("RegimenFiscal")> _
        Public Property RegimenFiscal() As ComprobanteEmisorRegimenFiscal()
            Get
                Return Me.regimenFiscalField
            End Get
            Set(value As ComprobanteEmisorRegimenFiscal())
                Me.regimenFiscalField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set(value As String)
                Me.rfcField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set(value As String)
                Me.nombreField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class t_UbicacionFiscal

        Private calleField As String

        Private noExteriorField As String

        Private noInteriorField As String

        Private coloniaField As String

        Private localidadField As String

        Private referenciaField As String

        Private municipioField As String

        Private estadoField As String

        Private paisField As String

        Private codigoPostalField As String

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property calle() As String
            Get
                Return Me.calleField
            End Get
            Set(value As String)
                Me.calleField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noExterior() As String
            Get
                Return Me.noExteriorField
            End Get
            Set(value As String)
                Me.noExteriorField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noInterior() As String
            Get
                Return Me.noInteriorField
            End Get
            Set(value As String)
                Me.noInteriorField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set(value As String)
                Me.coloniaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set(value As String)
                Me.localidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set(value As String)
                Me.referenciaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property municipio() As String
            Get
                Return Me.municipioField
            End Get
            Set(value As String)
                Me.municipioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set(value As String)
                Me.estadoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set(value As String)
                Me.paisField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property codigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set(value As String)
                Me.codigoPostalField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class t_InformacionAduanera

        Private numeroField As String

        Private fechaField As Date

        Private aduanaField As String

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set(value As String)
                Me.numeroField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")> _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set(value As Date)
                Me.fechaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property aduana() As String
            Get
                Return Me.aduanaField
            End Get
            Set(value As String)
                Me.aduanaField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class t_Ubicacion

        Private calleField As String

        Private noExteriorField As String

        Private noInteriorField As String

        Private coloniaField As String

        Private localidadField As String

        Private referenciaField As String

        Private municipioField As String

        Private estadoField As String

        Private paisField As String

        Private codigoPostalField As String

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property calle() As String
            Get
                Return Me.calleField
            End Get
            Set(value As String)
                Me.calleField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noExterior() As String
            Get
                Return Me.noExteriorField
            End Get
            Set(value As String)
                Me.noExteriorField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noInterior() As String
            Get
                Return Me.noInteriorField
            End Get
            Set(value As String)
                Me.noInteriorField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set(value As String)
                Me.coloniaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set(value As String)
                Me.localidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set(value As String)
                Me.referenciaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property municipio() As String
            Get
                Return Me.municipioField
            End Get
            Set(value As String)
                Me.municipioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set(value As String)
                Me.estadoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set(value As String)
                Me.paisField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property codigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set(value As String)
                Me.codigoPostalField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteEmisorRegimenFiscal

        Private regimenField As String

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Regimen() As String
            Get
                Return Me.regimenField
            End Get
            Set(value As String)
                Me.regimenField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteReceptor

        Private domicilioField As t_Ubicacion

        Private rfcField As String

        Private nombreField As String

        '''<comentarios/>
        Public Property Domicilio() As t_Ubicacion
            Get
                Return Me.domicilioField
            End Get
            Set(value As t_Ubicacion)
                Me.domicilioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set(value As String)
                Me.rfcField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set(value As String)
                Me.nombreField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConcepto

        Private itemsField() As Object

        Private cantidadField As Decimal

        Private unidadField As String

        Private noIdentificacionField As String

        Private descripcionField As String

        Private valorUnitarioField As Decimal

        Private importeField As Decimal

        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("ComplementoConcepto", GetType(ComprobanteConceptoComplementoConcepto)), _
         System.Xml.Serialization.XmlElementAttribute("CuentaPredial", GetType(ComprobanteConceptoCuentaPredial)), _
         System.Xml.Serialization.XmlElementAttribute("InformacionAduanera", GetType(t_InformacionAduanera)), _
         System.Xml.Serialization.XmlElementAttribute("Parte", GetType(ComprobanteConceptoParte))> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(value As Object())
                Me.itemsField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set(value As Decimal)
                Me.cantidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set(value As String)
                Me.unidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set(value As String)
                Me.noIdentificacionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set(value As String)
                Me.descripcionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set(value As Decimal)
                Me.valorUnitarioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoComplementoConcepto

        Private anyField() As System.Xml.XmlElement

        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoCuentaPredial

        Private numeroField As String

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set(value As String)
                Me.numeroField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoParte

        Private informacionAduaneraField() As t_InformacionAduanera

        Private cantidadField As Decimal

        Private unidadField As String

        Private noIdentificacionField As String

        Private descripcionField As String

        Private valorUnitarioField As Decimal

        Private valorUnitarioFieldSpecified As Boolean

        Private importeField As Decimal

        Private importeFieldSpecified As Boolean

        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")> _
        Public Property InformacionAduanera() As t_InformacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set(value As t_InformacionAduanera())
                Me.informacionAduaneraField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set(value As Decimal)
                Me.cantidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set(value As String)
                Me.unidadField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set(value As String)
                Me.noIdentificacionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set(value As String)
                Me.descripcionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set(value As Decimal)
                Me.valorUnitarioField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property valorUnitarioSpecified() As Boolean
            Get
                Return Me.valorUnitarioFieldSpecified
            End Get
            Set(value As Boolean)
                Me.valorUnitarioFieldSpecified = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(value As Decimal)
                Me.importeField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property importeSpecified() As Boolean
            Get
                Return Me.importeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.importeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestos

        Private retencionesField() As ComprobanteImpuestosRetencion

        Private trasladosField() As ComprobanteImpuestosTraslado

        Private totalImpuestosRetenidosField As Decimal

        Private totalImpuestosRetenidosFieldSpecified As Boolean

        Private totalImpuestosTrasladadosField As Decimal

        Private totalImpuestosTrasladadosFieldSpecified As Boolean

        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=False)> _
        Public Property Retenciones() As ComprobanteImpuestosRetencion()
            Get
                Return Me.retencionesField
            End Get
            Set(value As ComprobanteImpuestosRetencion())
                Me.retencionesField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=False)> _
        Public Property Traslados() As ComprobanteImpuestosTraslado()
            Get
                Return Me.trasladosField
            End Get
            Set(value As ComprobanteImpuestosTraslado())
                Me.trasladosField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property totalImpuestosRetenidos() As Decimal
            Get
                Return Me.totalImpuestosRetenidosField
            End Get
            Set(value As Decimal)
                Me.totalImpuestosRetenidosField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property totalImpuestosRetenidosSpecified() As Boolean
            Get
                Return Me.totalImpuestosRetenidosFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalImpuestosRetenidosFieldSpecified = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property totalImpuestosTrasladados() As Decimal
            Get
                Return Me.totalImpuestosTrasladadosField
            End Get
            Set(value As Decimal)
                Me.totalImpuestosTrasladadosField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property totalImpuestosTrasladadosSpecified() As Boolean
            Get
                Return Me.totalImpuestosTrasladadosFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalImpuestosTrasladadosFieldSpecified = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestosRetencion

        Private impuestoField As ComprobanteImpuestosRetencionImpuesto

        Private importeField As Decimal

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property impuesto() As ComprobanteImpuestosRetencionImpuesto
            Get
                Return Me.impuestoField
            End Get
            Set(value As ComprobanteImpuestosRetencionImpuesto)
                Me.impuestoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Public Enum ComprobanteImpuestosRetencionImpuesto

        '''<comentarios/>
        ISR

        '''<comentarios/>
        IVA
    End Enum

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestosTraslado

        Private impuestoField As ComprobanteImpuestosTrasladoImpuesto

        Private tasaField As Decimal

        Private importeField As Decimal

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property impuesto() As ComprobanteImpuestosTrasladoImpuesto
            Get
                Return Me.impuestoField
            End Get
            Set(value As ComprobanteImpuestosTrasladoImpuesto)
                Me.impuestoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property tasa() As Decimal
            Get
                Return Me.tasaField
            End Get
            Set(value As Decimal)
                Me.tasaField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Public Enum ComprobanteImpuestosTrasladoImpuesto

        '''<comentarios/>
        IVA

        '''<comentarios/>
        IEPS
    End Enum

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteComplemento

        Private anyField() As System.Xml.XmlElement

        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteAddenda

        Private anyField() As System.Xml.XmlElement

        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Public Enum ComprobanteTipoDeComprobante

        '''<comentarios/>
        ingreso

        '''<comentarios/>
        egreso

        '''<comentarios/>
        traslado
    End Enum
End Namespace
