'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace CFDI32.TimbreFiscal

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital", IsNullable:=False)> _
    Partial Public Class TimbreFiscalDigital

        Private versionField As String

        Private uUIDField As String

        Private fechaTimbradoField As Date

        Private selloCFDField As String

        Private noCertificadoSATField As String

        Private selloSATField As String

        Public Sub New()
            MyBase.New()
            Me.versionField = "1.0"
        End Sub

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(value As String)
                Me.versionField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set(value As String)
                Me.uUIDField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property FechaTimbrado() As Date
            Get
                Return Me.fechaTimbradoField
            End Get
            Set(value As Date)
                Me.fechaTimbradoField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property selloCFD() As String
            Get
                Return Me.selloCFDField
            End Get
            Set(value As String)
                Me.selloCFDField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property noCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set(value As String)
                Me.noCertificadoSATField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property selloSAT() As String
            Get
                Return Me.selloSATField
            End Get
            Set(value As String)
                Me.selloSATField = value
            End Set
        End Property
    End Class
End Namespace
