//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionCAT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div id=""frame""> <div class=""dleft""><img src=""http://urgi.com.mx/wp-content/uploads/2015/12/Urgi_m.png"" alt=""URGI"" /> </div> <div class=""dright""><h1>Bienvenido al Sistema de Facturaci&oacute;n Aero Contaxi</h1></div> <br/> <div style=""text-align:justify""> Recientemente ha solicitado registrarse como usuario en el sitio facturacion.urgi.com.mx para concluir el proceso de registro es necesario validar su cuenta de correo electr&oacute;nico. <br/><br/> Le invitamos a dar clic <br/><br/> <a href=""{0}?token={1}&cuenta={2}"">AQUI PARA ACTIVAR SU CUENTA</a> </div> </div>")]
        public string MailRegistroBody {
            get {
                return ((string)(this["MailRegistroBody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ha elegido cambiar su contraseña, la nueva contraseña es: <br><br><b>{0}</b><br><" +
            "br>Ingrese utilizando esta nueva contraseña y en la sección de  \"Mis Datos\" podr" +
            "á cambiarla a la contraseña de su preferencia.")]
        public string MailRecuperacionBody {
            get {
                return ((string)(this["MailRecuperacionBody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Recuperación de contraseña")]
        public string MailRecuperacionAsunto {
            get {
                return ((string)(this["MailRecuperacionAsunto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bienvenido al sitio de Facturación de Aero Contaxi!")]
        public string MailRegistroAsunto {
            get {
                return ((string)(this["MailRegistroAsunto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sus datos han sido recibidos por el sistema, sin embargo es necesario que confirm" +
            "e su dirección de correo electrónico, por favor revise la siguiente cuenta de co" +
            "rreo electrónico <strong>{0}</strong> y siga las instrucciones para activar su c" +
            "uenta.")]
        public string MensajeRegistroOK {
            get {
                return ((string)(this["MensajeRegistroOK"]));
            }
        }
    }
}
